# Generated by Django 5.1 on 2024-08-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0003_alter_menu_menu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_items_name', models.CharField(max_length=100)),
                ('menu_items_desc', models.TextField()),
                ('menu_items_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuItems', to='restaurantApp.menu')),
            ],
        ),
    ]
