# Generated by Django 5.1 on 2024-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('employee', 'Employee')], max_length=10, null=True),
        ),
    ]
